### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by ClaudiuCreanga** [motou/magento2-store-locator-stockists-extension#55]
Looking for a maintainer to take control of this project and move it forward. There are new releases of magento2 and apparently some things stopped working, i.e. issue https://github.com/ClaudiuCreanga/magento2-store-locator-stockists-extension/issues/29. As I no longer work with magento, I don't have time to debug the issue. Anyone interested, post your availability here.

**Comment by motou** [comment]
I have some projects that still use this extension. So I am willing to take over the maintainer tasks.

**Comment by motou** [comment]
Cleaning up the old issues
